# nightmare/plan/verification.cr
# Copyright (C) 2026 Cam Carroll
# Licensed under the AGPL-3.0. See LICENSE for details.

require "xml"
require "./models"
require "./run_state"

module Nightmare::Plan
  class VerificationError < Exception
  end

  record VerificationResult,
    passed : Bool,
    summary : String,
    new_failures : Array(String),
    disappeared_tests : Array(String),
    all_tests : Array(String),
    exit_code : Int32

  abstract class VerificationParser
    abstract def parse(output : String, reports_dir : String? = nil) : Tuple(Array(String), Array(String))
  end

  # Parses JUnit XML reports generated by test runners (e.g. crystal spec --junit_output)
  class JUnitParser < VerificationParser
    def parse(output : String, reports_dir : String? = nil) : Tuple(Array(String), Array(String))
      all_tests = [] of String
      failing_tests = [] of String

      xml_files = [] of String
      if dir = reports_dir
        if Dir.exists?(dir)
          Dir.glob(File.join(dir, "**", "*.xml")).each { |f| xml_files << f }
        end
      end

      if xml_files.empty?
        # Try parsing output directly if it looks like XML
        if output.includes?("<testsuite") || output.includes?("<testcase")
          parse_xml_string(output, all_tests, failing_tests)
        end
      else
        xml_files.each do |file_path|
          content = File.read(file_path)
          parse_xml_string(content, all_tests, failing_tests)
        end
      end

      {all_tests.uniq, failing_tests.uniq}
    end

    private def parse_xml_string(xml_text : String, all_tests : Array(String), failing_tests : Array(String)) : Nil
      begin
        doc = XML.parse(xml_text)
        # Find all testcase nodes
        doc.xpath_nodes("//testcase").each do |node|
          classname = node["classname"]? || ""
          name = node["name"]? || ""
          full_path = if classname.empty?
                        name
                      else
                        "#{classname} > #{name}"
                      end
          next if full_path.empty?

          all_tests << full_path

          # Check for failure or error child nodes
          has_failure = node.xpath_nodes("failure").size > 0 || node.xpath_nodes("error").size > 0
          if has_failure
            failing_tests << full_path
          end
        end
      rescue ex
        # XML parse error fallback
      end
    end
  end

  # Fallback exit-code parser
  class ExitCodeParser < VerificationParser
    def parse(output : String, reports_dir : String? = nil) : Tuple(Array(String), Array(String))
      # Exit code parser has no granular test identity paths
      {[] of String, [] of String}
    end
  end

  class VerificationEngine
    getter parsers : Hash(String, VerificationParser)

    def initialize
      @parsers = {
        "junit"     => JUnitParser.new,
        "exit_code" => ExitCodeParser.new,
      }
    end

    def register_parser(name : String, parser : VerificationParser) : Nil
      @parsers[name] = parser
    end

    # Pre-flight baseline capture
    def capture_baseline(
      config : BaselineConfig,
      cwd : String,
      cache_dir : String
    ) : BaselineState
      cmd = config.command
      if cmd.empty?
        return BaselineState.new(0, config.expected_known_failures, [] of String)
      end

      out_str, err_str, exit_code = run_subprocess(cmd, cwd, cache_dir)

      parser_name = config.parser || "junit"
      parser = @parsers[parser_name]? || @parsers["exit_code"]

      reports_dir = extract_reports_dir(cmd)
      all_tests, failing_tests = parser.parse(out_str, reports_dir)

      # If parser didn't find XML, but command succeeded, all is well
      total = all_tests.size

      # Baseline sanity assertions:
      if total == 0 && exit_code != 0
        raise VerificationError.new(
          "Baseline command failed before plan execution began (exit code #{exit_code}):\n#{err_str}\n#{out_str}"
        )
      end

      if total > 0 && failing_tests.size == total
        raise VerificationError.new(
          "Baseline sanity assertion failed: 100% of tests are failing (#{failing_tests.size}/#{total}). Fix codebase setup before running plan."
        )
      end

      # Merge any explicitly declared expected known failures
      known = (failing_tests + config.expected_known_failures).uniq

      BaselineState.new(
        total_tests: total,
        known_failing_tests: known,
        all_test_descriptions: all_tests
      )
    end

    # Evaluates the verification gate for an item
    def evaluate_gate(
      config : VerificationConfig,
      baseline : BaselineState,
      cwd : String,
      cache_dir : String
    ) : VerificationResult
      case config.kind
      when VerificationKind::None
        VerificationResult.new(
          passed: true,
          summary: "Verification skipped (kind: none)",
          new_failures: [] of String,
          disappeared_tests: [] of String,
          all_tests: [] of String,
          exit_code: 0
        )
      when VerificationKind::DiffNonEmpty
        # Checked directly by worktree diff check
        VerificationResult.new(
          passed: true,
          summary: "Diff non-empty verification",
          new_failures: [] of String,
          disappeared_tests: [] of String,
          all_tests: [] of String,
          exit_code: 0
        )
      when VerificationKind::Compile
        cmd = config.command
        out_str, err_str, exit_code = run_subprocess(cmd, cwd, cache_dir)
        passed = (exit_code == 0)
        summary = if passed
                    "Compilation succeeded"
                  else
                    "Compilation failed (exit #{exit_code}):\n#{err_str.empty? ? out_str : err_str}"
                  end
        VerificationResult.new(
          passed: passed,
          summary: summary,
          new_failures: [] of String,
          disappeared_tests: [] of String,
          all_tests: [] of String,
          exit_code: exit_code
        )
      when VerificationKind::Command
        cmd = config.command
        out_str, err_str, exit_code = run_subprocess(cmd, cwd, cache_dir)

        parser_name = config.parser || "junit"
        parser = @parsers[parser_name]? || @parsers["exit_code"]

        reports_dir = extract_reports_dir(cmd)
        current_all, current_failing = parser.parse(out_str, reports_dir)

        # 1. Monotonicity check
        disappeared = baseline.all_test_descriptions - current_all
        if !config.allows_test_removal && !disappeared.empty?
          return VerificationResult.new(
            passed: false,
            summary: "Gate Failure: Test-set monotonicity violation (#{disappeared.size} tests disappeared: #{disappeared.first(3).join(", ")})",
            new_failures: current_failing,
            disappeared_tests: disappeared,
            all_tests: current_all,
            exit_code: exit_code
          )
        end

        # 2. Differential failure check
        new_failures = current_failing - baseline.known_failing_tests

        passed = if config.expect == "no_new_failures"
                   if current_all.empty?
                     # Degrade to raw exit code if parser returned no tests
                     exit_code == 0
                   else
                     new_failures.empty?
                   end
                 else
                   # expect pass
                   exit_code == 0 && current_failing.empty?
                 end

        summary = if passed
                    "Verification passed: #{current_all.size} tests ran, 0 new failures"
                  else
                    if !new_failures.empty?
                      "Verification failed: #{new_failures.size} new failures:\n#{new_failures.join("\n")}"
                    else
                      "Verification failed (exit #{exit_code}):\n#{err_str.empty? ? out_str : err_str}"
                    end
                  end

        VerificationResult.new(
          passed: passed,
          summary: summary,
          new_failures: new_failures,
          disappeared_tests: disappeared,
          all_tests: current_all,
          exit_code: exit_code
        )
      else
        VerificationResult.new(true, "Unknown kind", [] of String, [] of String, [] of String, 0)
      end
    end

    private def run_subprocess(cmd : Array(String), cwd : String, cache_dir : String) : Tuple(String, String, Int32)
      return {"", "", 0} if cmd.empty?

      env = {
        "CRYSTAL_CACHE_DIR" => cache_dir,
        "CI"                => "1",
        "NO_COLOR"          => "1",
      }

      out_io = IO::Memory.new
      err_io = IO::Memory.new

      status = Process.run(
        cmd.first,
        cmd[1..],
        chdir: cwd,
        env: env,
        output: out_io,
        error: err_io
      )

      {out_io.to_s, err_io.to_s, status.exit_code}
    end

    private def extract_reports_dir(cmd : Array(String)) : String?
      cmd.each_with_index do |token, i|
        if token == "--junit_output" && i + 1 < cmd.size
          return cmd[i + 1]
        end
      end
      nil
    end
  end
end
